In [1]:
# Import libraries

import pandas as pd
import numpy as np 
import os

Importing Dataframes

In [2]:
# Defining path

path = r'/Users/lilia.verbenkogmail.com/04-08-2023 Instacart Basket Analysis'

In [3]:
# Importing ords_prods_merged

ords_prods_merged = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_updated.pkl'))

In [4]:
# Creating a subset df of the first one million entries


df = ords_prods_merged[:1000000]

In [5]:
ords_prods_merged.head(10)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,order_hour_of_day_loc,busiest_hours
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders
1,2398795,1,prior,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders
2,473747,1,prior,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders
3,2254736,1,prior,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy,NaN,Average orders
4,431534,1,prior,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders
5,3367565,1,prior,6,2,7,19.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders
6,550135,1,prior,7,1,9,20.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders
7,3108588,1,prior,8,1,14,14.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders
8,2295261,1,prior,9,1,16,0.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders
9,2550362,1,prior,10,4,8,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy,NaN,Average orders

In [6]:
# Using groupby() function

df.groupby('product_name')

In [7]:
# Aggregating Data with agg()

df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [8]:
# Aggregating Data without agg()

df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [9]:
# Multiple Aggregations using agg()

df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

In [10]:
# Aggregating Data with transform()

ords_prods_merged['max_order'] = ords_prods_merged.groupby(['user_id'])['order_number'].transform(np.max)

In [11]:
ords_prods_merged.head(100)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,order_hour_of_day_loc,busiest_hours,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders,10
2,473747,1,prior,3,3,12,21.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,NaN,Average orders,10
4,431534,1,prior,5,4,15,28.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3226575,360,prior,1,5,12,NaN,196,1,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,3
96,1469869,377,prior,3,5,17,3.0,196,9,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Fewest orders,3
97,1927023,387,prior,2,4,10,22.0,196,3,0,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,8
98,858092,420,prior,4,1,19,30.0,196,2,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,NaN,Fewest orders,22
99,119314,420,prior,5,3,19,16.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,NaN,Fewest orders,22

In [12]:
pd.options.display.max_rows = None

In [13]:
ords_prods_merged.head(100)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,order_hour_of_day_loc,busiest_hours,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders,10
2,473747,1,prior,3,3,12,21.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,NaN,Average orders,10
4,431534,1,prior,5,4,15,28.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,10
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,10
6,550135,1,prior,7,1,9,20.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,10
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,10
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,10
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,NaN,Average orders,10
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,22
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,22
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,22
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,22
14,487368,15,prior,22,1,10,14.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,22
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,9
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,9
17,532817,19,prior,7,4,17,6.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,NaN,Fewest orders,9
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,33
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders,20
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,20
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,11
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,11
23,2497897,52,prior,1,1,9,NaN,196,4,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27
26,580568,52,prior,5,2,10,8.0,196,6,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,27
28,342306,52,prior,9,1,11,7.0,196,5,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27
31,944694,52,prior,12,1,16,6.0,196,7,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27
35,180919,52,prior,19,3,8,8.0,196,4,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders,27
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27
37,3205960,67,prior,1,3,11,NaN,196,1,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,24
38,970922,67,prior,2,1,15,5.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24
39,596585,67,prior,3,1,13,7.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,24
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,24
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24
49,551869,67,prior,14,1,9,7.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24
50,768572,67,prior,16,4,10,9.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,24
51,150528,67,prior,18,5,16,4.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24
52,29758,67,prior,19,0,14,9.0,196,2,1,...,77,7,9.0,both,Mid-range product,Busiest day,Busiest day,Most orders,Most orders,24
53,1558976,67,prior,21,1,9,5.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24
54,863974,67,prior,22,1,11,14.0,196,3,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24
55,2308399,67,prior,23,1,14,14.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24
56,2759128,81,prior,3,1,9,14.0,196,2,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,7
57,1812985,81,prior,5,2,20,30.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Fewest orders,7
58,1889835,82,prior,1,3,15,NaN,196,6,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,19
59,499460,82,prior,3,5,10,5.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,19
60,2728456,82,prior,4,0,11,16.0,196,1,1,...,77,7,9.0,both,Mid-range product,Busiest day,Busiest day,Most orders,Most orders,19
61,2653743,82,prior,6,4,9,13.0,196,5,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,19
62,1358880,82,prior,9,1,10,30.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,19
63,343588,82,prior,10,2,11,1.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,19
64,3034663,82,prior,15,2,11,12.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,19
65,147262,82,prior,18,1,13,7.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,19
66,3144004,82,prior,19,2,15,8.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,19
67,2126069,98,prior,3,0,9,25.0,196,7,0,...,77,7,9.0,both,Mid-range product,Busiest day,Busiest day,Most orders,Most orders,14
68,2210120,98,prior,7,5,14,5.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
69,681011,98,prior,9,3,9,30.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,14
70,2846344,98,prior,11,4,13,15.0,196,2,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,14
71,747431,98,prior,12,6,13,30.0,196,4,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14
72,2383054,98,prior,13,4,11,30.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,14
73,1993729,98,prior,14,5,8,8.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,14
74,1403849,109,prior,3,3,17,9.0,196,5,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,NaN,Fewest orders,6
75,520620,120,prior,1,3,11,NaN,196,2,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,3
76,3273029,120,prior,3,2,8,19.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,3
77,1861943,185,prior,2,1,12,25.0,196,10,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,6
78,2040988,195,prior,1,1,14,NaN,196,2,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,58
79,1680569,195,prior,8,1,9,4.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,58
80,276171,195,prior,19,5,11,3.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,58
81,2744976,195,prior,22,5,10,7.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,58
82,2781919,195,prior,25,1,14,4.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,58
83,1738718,195,prior,31,2,8,4.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,58
84,3058369,195,prior,34,3,10,6.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,58
85,1485596,195,prior,37,2,15,0.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,58
86,417035,195,prior,40,3,16,2.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,58
87,1615297,195,prior,47,5,10,2.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,58
88,1765587,195,prior,52,3,12,2.0,196,3,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,58
89,745908,195,prior,57,4,11,3.0,196,3,1,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,58
90,2505656,222,prior,17,2,12,1.0,196,2,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,70
91,3268370,222,prior,38,5,15,1.0,196,6,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,70
92,2016711,290,prior,9,5,19,6.0,196,8,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Fewest orders,51
93,2706088,290,prior,28,6,10,7.0,196,16,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,51
94,1952286,331,prior,6,5,16,30.0,196,8,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,8
95,3226575,360,prior,1,5,12,NaN,196,1,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,3
96,1469869,377,prior,3,5,17,3.0,196,9,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,NaN,Fewest orders,3
97,1927023,387,prior,2,4,10,22.0,196,3,0,...,77,7,9.0,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,8
98,858092,420,prior,4,1,19,30.0,196,2,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest day,NaN,Fewest orders,22
99,119314,420,prior,5,3,19,16.0,196,2,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Least busy,NaN,Fewest orders,22

In [14]:
ords_prods_merged.loc[ords_prods_merged['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
ords_prods_merged.loc[(ords_prods_merged['max_order'] <= 40) & (ords_prods_merged['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
ords_prods_merged.loc[ords_prods_merged['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [15]:
ords_prods_merged['loyalty_flag'].value_counts()

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [16]:
ords_prods_merged[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

#### Step 2. Aggregating the mean of the “order_number” column grouped by “department_id” for the entire dataframe.

In [17]:
ords_prods_merged.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

#### Step 3. Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code.

#### Answer: Comparing the subset to the whole data frame, it has been observed that, excluding the mean for department_id 17, the average mean value of each order_number within the subset (1000000) is higher than the average mean value of the entire data frame.

#### Step 4. #### Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.

#### Answer: Output 17

#### Step 5. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category. 
#### Determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [18]:
ords_prods_merged.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

When looking at the mean prices, it is observed that loyal customers have the lowest average price, followed by regular customers, and new customers. However, it's important to note that the maximum price is the same (99999.0) for all three customer types, which might indicate outliers or errors in the data. The minimum price is consistent across customer types as well (1.0).

To sum up, it looks like loyal customers tend to have the lowest average prices, followed by regular customers and new customers. The consistent maximum price across all customer types might warrant further investigation into the validity of that value.

#### Step 6. Create a spending flag for each user based on the average price across all their orders using the following criteria:
- If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
- If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [25]:
# Caclucating the average price

ords_prods_merged['average_price'] = ords_prods_merged.groupby(['user_id'])['prices'].transform(np.mean)

In [26]:
ords_prods_merged.head(50)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,_merge,price_range_loc,busiest_day,busiest_days,order_hour_of_day_loc,busiest_hours,max_order,loyalty_flag,spending_flag,average_price
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,10,New customer,Low spender,6.367797
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders,10,New customer,Low spender,6.367797
2,473747,1,prior,3,3,12,21.0,196,1,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,10,New customer,Low spender,6.367797
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,NaN,Average orders,10,New customer,Low spender,6.367797
4,431534,1,prior,5,4,15,28.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,10,New customer,Low spender,6.367797
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,10,New customer,Low spender,6.367797
6,550135,1,prior,7,1,9,20.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,10,New customer,Low spender,6.367797
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,10,New customer,Low spender,6.367797
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,10,New customer,Low spender,6.367797
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,NaN,Average orders,10,New customer,Low spender,6.367797
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,22,Regular customer,Low spender,3.980556
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,22,Regular customer,Low spender,3.980556
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,22,Regular customer,Low spender,3.980556
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,22,Regular customer,Low spender,3.980556
14,487368,15,prior,22,1,10,14.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,22,Regular customer,Low spender,3.980556
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,9,New customer,Low spender,8.372059
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,9,New customer,Low spender,8.372059
17,532817,19,prior,7,4,17,6.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,NaN,Fewest orders,9,New customer,Low spender,8.372059
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,33,Regular customer,Low spender,7.012683
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders,20,Regular customer,Low spender,8.137793
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,20,Regular customer,Low spender,8.137793
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,11,Regular customer,Low spender,7.444898
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,11,Regular customer,Low spender,7.444898
23,2497897,52,prior,1,1,9,NaN,196,4,0,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27,Regular customer,Low spender,6.356287
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27,Regular customer,Low spender,6.356287
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27,Regular customer,Low spender,6.356287
26,580568,52,prior,5,2,10,8.0,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,27,Regular customer,Low spender,6.356287
28,342306,52,prior,9,1,11,7.0,196,5,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27,Regular customer,Low spender,6.356287
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
31,944694,52,prior,12,1,16,6.0,196,7,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27,Regular customer,Low spender,6.356287
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
35,180919,52,prior,19,3,8,8.0,196,4,1,...,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders,27,Regular customer,Low spender,6.356287
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
37,3205960,67,prior,1,3,11,NaN,196,1,0,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
38,970922,67,prior,2,1,15,5.0,196,2,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
39,596585,67,prior,3,1,13,7.0,196,2,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
49,551869,67,prior,14,1,9,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790

In [29]:
 # Creating spending flags

ords_prods_merged.loc[ords_prods_merged['average_price'] < 10, 'spending_flag'] = 'Low spender'

ords_prods_merged.loc[ords_prods_merged['average_price'] >= 10, 'spending_flag'] = 'High spender'

In [31]:
ords_prods_merged.head(100)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,_merge,price_range_loc,busiest_day,busiest_days,order_hour_of_day_loc,busiest_hours,max_order,loyalty_flag,spending_flag,average_price
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,10,New customer,Low spender,6.367797
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders,10,New customer,Low spender,6.367797
2,473747,1,prior,3,3,12,21.0,196,1,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,10,New customer,Low spender,6.367797
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,NaN,Average orders,10,New customer,Low spender,6.367797
4,431534,1,prior,5,4,15,28.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,10,New customer,Low spender,6.367797
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,10,New customer,Low spender,6.367797
6,550135,1,prior,7,1,9,20.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,10,New customer,Low spender,6.367797
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,10,New customer,Low spender,6.367797
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,10,New customer,Low spender,6.367797
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,NaN,Average orders,10,New customer,Low spender,6.367797
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,22,Regular customer,Low spender,3.980556
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,22,Regular customer,Low spender,3.980556
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,22,Regular customer,Low spender,3.980556
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,22,Regular customer,Low spender,3.980556
14,487368,15,prior,22,1,10,14.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,22,Regular customer,Low spender,3.980556
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,9,New customer,Low spender,8.372059
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,9,New customer,Low spender,8.372059
17,532817,19,prior,7,4,17,6.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,NaN,Fewest orders,9,New customer,Low spender,8.372059
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,33,Regular customer,Low spender,7.012683
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders,20,Regular customer,Low spender,8.137793
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,20,Regular customer,Low spender,8.137793
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,11,Regular customer,Low spender,7.444898
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,11,Regular customer,Low spender,7.444898
23,2497897,52,prior,1,1,9,NaN,196,4,0,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27,Regular customer,Low spender,6.356287
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27,Regular customer,Low spender,6.356287
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27,Regular customer,Low spender,6.356287
26,580568,52,prior,5,2,10,8.0,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,27,Regular customer,Low spender,6.356287
28,342306,52,prior,9,1,11,7.0,196,5,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27,Regular customer,Low spender,6.356287
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
31,944694,52,prior,12,1,16,6.0,196,7,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,27,Regular customer,Low spender,6.356287
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
35,180919,52,prior,19,3,8,8.0,196,4,1,...,both,Mid-range product,Regularly busy,Least busy,NaN,Average orders,27,Regular customer,Low spender,6.356287
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,27,Regular customer,Low spender,6.356287
37,3205960,67,prior,1,3,11,NaN,196,1,0,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
38,970922,67,prior,2,1,15,5.0,196,2,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
39,596585,67,prior,3,1,13,7.0,196,2,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
49,551869,67,prior,14,1,9,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
50,768572,67,prior,16,4,10,9.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
51,150528,67,prior,18,5,16,4.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,24,Regular customer,Low spender,7.656790
52,29758,67,prior,19,0,14,9.0,196,2,1,...,both,Mid-range product,Busiest day,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
53,1558976,67,prior,21,1,9,5.0,196,2,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
54,863974,67,prior,22,1,11,14.0,196,3,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
55,2308399,67,prior,23,1,14,14.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,24,Regular customer,Low spender,7.656790
56,2759128,81,prior,3,1,9,14.0,196,2,0,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,7,New customer,Low spender,8.165385
57,1812985,81,prior,5,2,20,30.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Fewest orders,7,New customer,Low spender,8.165385
58,1889835,82,prior,1,3,15,NaN,196,6,0,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,19,Regular customer,Low spender,6.441221
59,499460,82,prior,3,5,10,5.0,196,2,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,19,Regular customer,Low spender,6.441221
60,2728456,82,prior,4,0,11,16.0,196,1,1,...,both,Mid-range product,Busiest day,Busiest day,Most orders,Most orders,19,Regular customer,Low spender,6.441221
61,2653743,82,prior,6,4,9,13.0,196,5,1,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,19,Regular customer,Low spender,6.441221
62,1358880,82,prior,9,1,10,30.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,19,Regular customer,Low spender,6.441221
63,343588,82,prior,10,2,11,1.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,19,Regular customer,Low spender,6.441221
64,3034663,82,prior,15,2,11,12.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,19,Regular customer,Low spender,6.441221
65,147262,82,prior,18,1,13,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,19,Regular customer,Low spender,6.441221
66,3144004,82,prior,19,2,15,8.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,19,Regular customer,Low spender,6.441221
67,2126069,98,prior,3,0,9,25.0,196,7,0,...,both,Mid-range product,Busiest day,Busiest day,Most orders,Most orders,14,Regular customer,Low spender,8.028000
68,2210120,98,prior,7,5,14,5.0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14,Regular customer,Low spender,8.028000
69,681011,98,prior,9,3,9,30.0,196,1,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,14,Regular customer,Low spender,8.028000
70,2846344,98,prior,11,4,13,15.0,196,2,1,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,14,Regular customer,Low spender,8.028000
71,747431,98,prior,12,6,13,30.0,196,4,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,14,Regular customer,Low spender,8.028000
72,2383054,98,prior,13,4,11,30.0,196,1,1,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,14,Regular customer,Low spender,8.028000
73,1993729,98,prior,14,5,8,8.0,196,2,1,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,14,Regular customer,Low spender,8.028000
74,1403849,109,prior,3,3,17,9.0,196,5,0,...,both,Mid-range product,Regularly busy,Least busy,NaN,Fewest orders,6,New customer,Low spender,5.850725
75,520620,120,prior,1,3,11,NaN,196,2,0,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,3,New customer,Low spender,9.385714
76,3273029,120,prior,3,2,8,19.0,196,2,1,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,3,New customer,Low spender,9.385714
77,1861943,185,prior,2,1,12,25.0,196,10,0,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,6,New customer,Low spender,7.715000
78,2040988,195,prior,1,1,14,NaN,196,2,0,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
79,1680569,195,prior,8,1,9,4.0,196,2,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
80,276171,195,prior,19,5,11,3.0,196,2,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
81,2744976,195,prior,22,5,10,7.0,196,2,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
82,2781919,195,prior,25,1,14,4.0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest day,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
83,1738718,195,prior,31,2,8,4.0,196,2,1,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Average orders,58,Loyal customer,Low spender,7.149730
84,3058369,195,prior,34,3,10,6.0,196,2,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
85,1485596,195,prior,37,2,15,0.0,196,2,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
86,417035,195,prior,40,3,16,2.0,196,2,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
87,1615297,195,prior,47,5,10,2.0,196,2,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
88,1765587,195,prior,52,3,12,2.0,196,3,1,...,both,Mid-range product,Regularly busy,Least busy,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
89,745908,195,prior,57,4,11,3.0,196,3,1,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,58,Loyal customer,Low spender,7.149730
90,2505656,222,prior,17,2,12,1.0,196,2,0,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,70,Loyal customer,Low spender,6.862397
91,3268370,222,prior,38,5,15,1.0,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,70,Loyal customer,Low spender,6.862397
92,2016711,290,prior,9,5,19,6.0,196,8,0,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Fewest orders,51,Loyal customer,Low spender,7.285597
93,2706088,290,prior,28,6,10,7.0,196,16,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,51,Loyal customer,Low spender,7.285597
94,1952286,331,prior,6,5,16,30.0,196,8,0,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,8,New customer,Low spender,7.705128
95,3226575,360,prior,1,5,12,NaN,196,1,0,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,Most orders,3,New customer,High spender,10.006250
96,1469869,377,prior,3,5,17,3.0,196,9,0,...,both,Mid-range product,Regularly busy,Regularly busy,NaN,Fewest orders,3,New customer,Low spender,8.496552
97,1927023,387,prior,2,4,10,22.0,196,3,0,...,both,Mid-range product,Least busy,Least busy,Most orders,Most orders,8,New customer,Low spender,7.396610
98,858092,420,prior,4,1,19,30.0,196,2,0,...,both,Mid-range product,Regularly busy,Busiest day,NaN,Fewest orders,22,Regular customer,Low spender,7.387805
99,119314,420,prior,5,3,19,16.0,196,2,1,...,both,Mid-range product,Regularly busy,Least busy,NaN,Fewest orders,22,Regular customer,Low spender,7.387805

In [32]:
# Checking the frequency

ords_prods_merged['spending_flag'].value_counts(dropna = False)

Low spender     31770614
High spender      634245
Name: spending_flag, dtype: int64

#### Step 7. Determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:
- If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
- If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
- If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [37]:
def frequency_label(row):
    median_value = row['days_since_prior_order']
    
    if median_value > 20:
        return 'Non-frequent customer'
    elif 10 < median_value <= 20:
        return 'Regular customer'
    elif median_value <= 10:
        return 'Frequent customer'
    else:
        return 'NaN'

In [38]:
ords_prods_merged['order_frequency_flag'] = ords_prods_merged.apply(frequency_label, axis=1)

In [40]:
ords_prods_merged[['user_id', 'days_since_prior_order', 'order_frequency_flag']].head(60)

    user_id  days_since_prior_order   order_frequency_flag
0         1                     NaN                    NaN
1         1                    15.0       Regular customer
2         1                    21.0  Non-frequent customer
3         1                    29.0  Non-frequent customer
4         1                    28.0  Non-frequent customer
5         1                    19.0       Regular customer
6         1                    20.0       Regular customer
7         1                    14.0       Regular customer
8         1                     0.0      Frequent customer
9         1                    30.0  Non-frequent customer
10       15                     7.0      Frequent customer
11       15                     8.0      Frequent customer
12       15                     7.0      Frequent customer
13       15                     7.0      Frequent customer
14       15                    14.0       Regular customer
15       19                     6.0      Frequent customer
16       19                     8.0      Frequent customer
17       19                     6.0      Frequent customer
18       21                     6.0      Frequent customer
19       31                     7.0      Frequent customer
20       31                     8.0      Frequent customer
21       43                     4.0      Frequent customer
22       43                     3.0      Frequent customer
23       52                     NaN                    NaN
24       52                     7.0      Frequent customer
25       52                     7.0      Frequent customer
26       52                     8.0      Frequent customer
27       52                     8.0      Frequent customer
28       52                     7.0      Frequent customer
29       52                     8.0      Frequent customer
30       52                     7.0      Frequent customer
31       52                     6.0      Frequent customer
32       52                     8.0      Frequent customer
33       52                     6.0      Frequent customer
34       52                    14.0       Regular customer
35       52                     8.0      Frequent customer
36       52                    30.0  Non-frequent customer
37       67                     NaN                    NaN
38       67                     5.0      Frequent customer
39       67                     7.0      Frequent customer
40       67                     8.0      Frequent customer
41       67                     8.0      Frequent customer
42       67                     7.0      Frequent customer
43       67                     7.0      Frequent customer
44       67                     7.0      Frequent customer
45       67                     6.0      Frequent customer
46       67                     7.0      Frequent customer
47       67                     8.0      Frequent customer
48       67                     6.0      Frequent customer
49       67                     7.0      Frequent customer
50       67                     9.0      Frequent customer
51       67                     4.0      Frequent customer
52       67                     9.0      Frequent customer
53       67                     5.0      Frequent customer
54       67                    14.0       Regular customer
55       67                    14.0       Regular customer
56       81                    14.0       Regular customer
57       81                    30.0  Non-frequent customer
58       82                     NaN                    NaN
59       82                     5.0      Frequent customer

In [41]:
# Checking the frequency

ords_prods_merged['order_frequency_flag'].value_counts(dropna = False)

Frequent customer        19042466
Regular customer          6055803
Non-frequent customer     5230494
NaN                       2076096
Name: order_frequency_flag, dtype: int64

In [42]:
# Saving the pickle file

ords_prods_merged.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_merged_updated_2.pkl'))